FROM BASE_IMAGE AS habushu_builder
# Poetry and supporting plugin installations
RUN python -m ensurepip --upgrade && \
    pip install poetry==REPLACE_WITH_POETRY_VERSION && \
    poetry self add poetry-monorepo-dependency-plugin@REPLACE_WITH_POETRY_MONOREPO_DEPENDENCY_PLUGIN_VERSION && \
    poetry self add poetry-plugin-bundle@REPLACE_WITH_POETRY_PLUGIN_BUNDLE_VERSION

WORKDIR /work-dir
COPY CHOWN_PLACEHOLDER ANCHOR_DIRECTORY ./containerize-support/
RUN find . -type f -name pyproject.toml -exec sed -i 's|develop[[:blank:]]*=[[:blank:]]*true|develop = false|g' {} \;

USER root
WORKDIR /work-dir/containerize-support/REPLACE_WITH_SINGLE_REPO_PROJECT_DIR
ENV POETRY_CACHE_DIR="/.cache/pypoetry"

# export target project's virtual environment to /opt/venv
RUN --mount=type=cache,target=/.cache/pypoetry/ \
    poetry lock && \
    poetry bundle venv /opt/venv
