[project]
name = "habushu-uv-package-consumer"
version = "3.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Margaret Black", email = "black_margaret@bah.com" }
]
requires-python = ">=3.12.9"
dependencies = [
    "habushu-uv-package",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
habushu-uv-package = { path = "../habushu-uv-package", editable = true }

# Added by habushu-maven-plugin at 2025-04-14T10:35:55.964075 to use https://pypi.org/simple/ as source repository for installing dependencies
[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple/"
publish-url = "https://pypi.org/simple/"

[dependency-groups]
dev = [
    "ruff>=0.11.5",
]
