<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.technologybrewery.habushu</groupId>
        <artifactId>poetry</artifactId>
        <version>3.1.0</version>
    </parent>

    <name>habushu::Examples::Poetry::Publish to Development Repository</name>
    <description>Example of how to use Habushu to publish to a development repository</description>

    <artifactId>habushu-poetry-publish-to-dev-repo</artifactId>
    <packaging>habushu</packaging>

    <build>
        <directory>dist</directory>
    </build>

    <profiles>
        <profile>
            <id>deploy-example</id>
            <build>
                <directory>dist</directory>
                <plugins>
                    <plugin>
                        <groupId>org.technologybrewery.habushu</groupId>
                        <artifactId>habushu-maven-plugin</artifactId>
                        <extensions>true</extensions>
                        <configuration>
                            <useDevRepository>true</useDevRepository>
                            <devRepositoryId>private-repo</devRepositoryId>
                            <!-- Leave off simple/ suffix to enable seamless upload and download capabilities -->
                            <devRepositoryUrl>http://127.0.0.1:8080/</devRepositoryUrl>
                            <enableDevRepositoryUrlUploadSuffix>false</enableDevRepositoryUrlUploadSuffix>
                        </configuration>
                    </plugin>
                    <!-- The following two plugins have been added here to skip the default deploy process for habushu
                    for the sake of this example project -->
                    <plugin>
                        <groupId>org.sonatype.plugins</groupId>
                        <artifactId>nexus-staging-maven-plugin</artifactId>
                        <extensions>false</extensions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-deploy-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>default-deploy</id>
                                <phase>none</phase>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
