[project]
name = "extensions-python-dep-X"
#Note: we use .dev to test snapshots, and because the implied 0 of dev becomes explicit in the wheel name.
version = "1.0.0.dev"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Margaret Black", email = "black_margaret@bah.com" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
