[project]
name = "extensions-python-dep-X"
#Note: we use .dev to test snapshots, and because the implied 0 of dev becomes explicit in the wheel name.
version = "1.0.0.dev"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Margaret Black", email = "black_margaret@bah.com" }
]
requires-python = ">=3.12"
dependencies = [
    "aissemble-foundation-core-python==1.13.0.*",
    "renamed-python-dep-Y"
]

[[tool.uv.index]]
name = "dev-pypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit=true

[tool.uv.sources]
renamed-python-dep-Y = { path = "../../foundation/foundation-python-dep-Y", editable=true }
aissemble-foundation-core-python = { index = "dev-pypi" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
