[project]
name = "habushu-uv-install-from-dev-repo"
version = "3.4.1"
description = "Example of how to use Habushu to install a dependency from a development repository"
readme = "README.md"
authors = [
    { name = "Margaret Black", email = "black_margaret@bah.com" }
]
requires-python = ">=3.12"
dependencies = [
#    UNCOMMENT TO ENABLE FUNCTIONAL EXAMPLE
#    "habushu-uv-publish-to-dev-repo",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ruff>=0.11.4",
]

# Added by habushu-maven-plugin at 2025-04-09T10:35:14.766890 to use https://pypi.org/simple/ as source repository for installing dependencies
[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple/"
publish-url = "https://pypi.org/simple/"

# Added by habushu-maven-plugin at 2025-04-09T10:38:54.299633 to use http://127.0.0.1:8080/simple/ as source PyPi repository for installing dependencies
[[tool.uv.index]]
name = "private-repo"
url = "http://127.0.0.1:8080/simple/"
publish-url = "http://127.0.0.1:8080/"
