[project]
name = "habushu-uv-dependency-groups"
version = "3.0.0.dev"
description = "Example of how to use the dependency group related habushu-maven-plugin configurations with uv"
readme = "README.md"
authors = [
    { name = "Margaret Black", email = "black_margaret@bah.com" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ruff>=0.11.7",
]
groupa = [
    "numpy>=2.2.5",
]


# Added by habushu-maven-plugin at 2025-04-28T10:33:05.188637 to use https://pypi.org/simple/ as source repository for installing dependencies
[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple/"
publish-url = "https://pypi.org/simple/"

[tool.ruff.format]
indent-style="space"
line-ending="lf"
quote-style="preserve"
