[project]
authors = [
    {name = "James Choi", email = "choi_james@bah.com"},
]
license = {text = "MIT License"}
requires-python = ">=3.11"
dependencies = [
    "krausening>=20",
    "cryptography<43.0.0,>=42.0.0",
    "uvicorn[standard]>=0.19.0",
]
name = "habushu_uv_package"
version = "3.0.0.dev"
description = "Example of how to use the habushu-maven-plugin in a `uv`-based setting"
readme = "README.md"

[dependency-groups]
dev = [
    "behave>=1.2.6",
    "ruff>=0.9.9",
    "python-dotenv<1.0.0,>=0.20.0",
    "grpcio-tools>=1.48.0",
    "kappa-maki>=1.0.0",
    "ruff>=0.9.9",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


# Added by habushu-maven-plugin at 2025-02-25T14:51:50.809891 to use https://pypi.org/simple/ as source PyPi repository for installing dependencies
[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple/"

# Added by habushu-maven-plugin at 2025-02-25T14:51:50.811821 to use https://test.pypi.org/simple/ as source PyPi repository for installing dependencies
[[tool.uv.index]]
name = "dev-pypi"
url = "https://test.pypi.org/simple/"

[tool.ruff.lint]
ignore = ["E4","E7","F"]

[tool.ruff.format]
indent-style="space"
line-ending="lf"
quote-style="preserve"
