<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.technologybrewery.habushu</groupId>
        <artifactId>uv</artifactId>
        <version>3.1.1</version>
    </parent>

    <name>habushu::Examples::uv::Containerize Dependencies</name>
    <description>Example of how to use the containerize dependencies goal on an uv project</description>

    <artifactId>habushu-uv-containerize</artifactId>
    <packaging>docker-build</packaging>

    <build>
        <plugins>
            <plugin>
                <groupId>org.technologybrewery.habushu</groupId>
                <artifactId>habushu-maven-plugin</artifactId>
                <version>${project.version}</version>
                <executions>
                    <execution>
                        <id>dockerize</id>
                        <goals>
                            <goal>containerize-dependencies</goal>
                        </goals>
                        <phase>prepare-package</phase>
                        <configuration>
                            <dockerfile>src/main/resources/docker/Dockerfile</dockerfile>
                            <dockerBuilderBase>docker.io/python:3.12</dockerBuilderBase>
                            <dockerFinalBase>docker.io/python:3.12-slim</dockerFinalBase>
                            <updateDockerfile>true</updateDockerfile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.technologybrewery.fabric8</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <extensions>true</extensions>
                <configuration>
                    <skipPush>true</skipPush>
                </configuration>
            </plugin>
        </plugins>
    </build>


    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>habushu-uv-package-consumer</artifactId>
            <version>${project.version}</version>
            <type>habushu</type>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>custom-docker-template</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.technologybrewery.habushu</groupId>
                        <artifactId>habushu-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>dockerize</id>
                                <goals>
                                    <goal>containerize-dependencies</goal>
                                </goals>
                                <phase>prepare-package</phase>
                                <configuration>
                                    <dockerfile>src/main/resources/docker/Dockerfile</dockerfile>
                                    <dockerTemplatePath>src/main/resources/templates</dockerTemplatePath>
                                    <dockerUvBuilderStageTemplatePath>custom_uv_builder_stage_template.vm</dockerUvBuilderStageTemplatePath>
                                    <dockerUvFinalStageTemplatePath>custom_uv_final_stage_template.vm</dockerUvFinalStageTemplatePath>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.technologybrewery.fabric8</groupId>
                        <artifactId>docker-maven-plugin</artifactId>
                        <extensions>true</extensions>
                        <configuration>
                            <skipPush>true</skipPush>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
