[project]
name = "habushu_uv_containerize"
version = "3.0.0.dev"
description = "Example of how to use the habushu-maven-plugin to containerize an application"
authors = [{name = "Isaac Becerra Llanos", email = "ibecerrallanos@cpointe-inc.com"}]
requires-python = ">=3.11"
dependencies = [
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# Added by habushu-maven-plugin at 2025-04-09T09:49:15.815876 to use https://pypi.org/simple/ as source repository for installing dependencies
[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple/"
publish-url = "https://pypi.org/simple/"

[dependency-groups]
dev = [
    "ruff>=0.11.8",
]
