<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.technologybrewery.habushu</groupId>
        <artifactId>poetry</artifactId>
        <version>3.0.0-SNAPSHOT</version>
    </parent>

    <name>habushu::Examples::Poetry::Install from Development Repository</name>
    <description>Example of how to use Habushu to install a dependency from a development repository</description>

    <artifactId>habushu-poetry-install-from-dev-repo</artifactId>
    <packaging>habushu</packaging>

    <build>
        <directory>dist</directory>
        <plugins>
            <plugin>
                <groupId>org.technologybrewery.habushu</groupId>
                <artifactId>habushu-maven-plugin</artifactId>
                <configuration>
                    <deactivateMigrations>
                        <!--  Skip migration that removes empty TOML headers to keep functional example valid-->
                        <deactivateMigration>poetry-v2-remove-empty-toml-migration</deactivateMigration>
                    </deactivateMigrations>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>install-example</id>
            <build>
                <directory>dist</directory>
                <plugins>
                    <plugin>
                        <groupId>org.technologybrewery.habushu</groupId>
                        <artifactId>habushu-maven-plugin</artifactId>
                        <extensions>true</extensions>
                        <configuration>
                            <useDevRepository>true</useDevRepository>
                            <devRepositoryId>private-repo</devRepositoryId>
                            <!-- Leave off simple/ suffix to enable seamless upload and download capabilities -->
                            <devRepositoryUrl>http://127.0.0.1:8080/</devRepositoryUrl>
                            <enableDevRepositoryUrlUploadSuffix>false</enableDevRepositoryUrlUploadSuffix>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
