# This file is optional, but if you choose to use this file in a project, it should be included in version control to ensure consistent builds.
[virtualenvs]
in-project = true
use-poetry-python = false

[repositories.dev-pypi]
url = "https://test.pypi.org/legacy/"
