[tool.poetry]
packages = [{include = "habushu_poetry_add_to_project", from = "src"}]

[project]
name = "habushu-poetry-add-to-project"
version = "3.0.0.dev"
description = "This example demonstrates how to add Habushu to a new or existing Poetry project."
authors = [{name = "Margaret Black", email = "black_margaret@bah.com"}]
dynamic = ["version", "dependencies"]
readme = "README.md"
requires-python = ">=3.12,<4"

[tool.poetry.dependencies]

[tool.poetry.group.dev.dependencies]
behave = "^1.2.6"
kappa-maki = "^1.0.2"
ruff = ">=0.9.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


# Added by habushu-maven-plugin at 2025-02-25T15:38:56.068690 to use https://test.pypi.org/simple/ as source PyPi repository for installing dependencies
[[tool.poetry.source]]
name = "dev-pypi"
url = "https://test.pypi.org/simple/"
priority = "supplemental"

[tool.ruff.format]
indent-style="space"
line-ending="lf"
quote-style="preserve"

[tool.ruff.lint]
ignore = ["E4","E7","F"]
