package org.technologybrewery.habushu.exec;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;
import java.util.stream.Collectors;

import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.tuple.Pair;
import org.apache.maven.plugin.MojoExecutionException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Facilitates the execution of package manager commands.
 */
public abstract class AbstractCommandHelper {
    private static final Logger logger = LoggerFactory.getLogger(AbstractCommandHelper.class);

    protected File workingDirectory;

    protected String packageManagerCommand;


    public AbstractCommandHelper(File workingDirectory, String packageManagerCommand) {
        this.workingDirectory = workingDirectory;
        this.packageManagerCommand = packageManagerCommand;
    }
    /**
     * Executes a package manager command with the given arguments, logs the executed
     * command, and returns the resultant process output as a string. This method
     * should be utilized when performing downstream logic based on the output of a
     * command, or it is desirable to not show the command's generated
     * stdout.
     *
     * @param arguments
     * @return
     * @throws MojoExecutionException
     */
    public String execute(List<String> arguments) throws MojoExecutionException {
        if (logger.isInfoEnabled()) {
            logger.info("Executing " + packageManagerCommand + " command: {} {}", packageManagerCommand, StringUtils.join(arguments, " "));
        }
        ProcessExecutor executor = createPackageManagerExecutor(arguments);
        return executor.executeAndGetResult(logger);
    }

    /**
     * Executes a command with the given arguments, logs the executed
     * command, logs the stdout/stderr generated by the process, and returns the
     * process exit code. This method should be utilized when it is desirable to
     * immediately show all of the stdout/stderr produced by a command for
     * diagnostic purposes.
     *
     * @param arguments
     * @return
     * @throws MojoExecutionException
     */
    public int executeAndLogOutput(List<String> arguments) throws MojoExecutionException {
        if (logger.isInfoEnabled()) {
            logger.info("Executing " + packageManagerCommand + " command: {} {}", packageManagerCommand, StringUtils.join(arguments, " "));
        }
        ProcessExecutor executor = createPackageManagerExecutor(arguments);
        return executor.executeAndRedirectOutput(logger);
    }

    /**
     * Executes a command with the given arguments and environment variables,
     * logs the executed command and logs the stdout/stderr generated by the process.
     * This method should be utilized when environment variables are needed for the command,
     * and it is desirable to immediately show all the stdout/stderr produced by a command for
     * diagnostic purposes.
     *
     * @param arguments
     * @param environmentVariables
     */
    public void executeAndLogOutput(List<String> arguments, Map<String, String> environmentVariables) {
        if (logger.isInfoEnabled()) {
            logger.info("Executing " + packageManagerCommand + " command: {} {}", packageManagerCommand, StringUtils.join(arguments, " "));
        }
        ProcessExecutor executor = createPackageManagerExecutor(arguments, environmentVariables);
        executor.executeAndRedirectOutput(logger);
    }

    /**
     * Similar to {@link #executeAndLogOutput(List)}, except the executed 
     * command that is logged obfuscates/masks any given command arguments that are
     * marked as sensitive. This method should be utilized if any command
     * line arguments contain sensitive values that are not desirable to log, such
     * as passwords.
     *
     * @param argAndIsSensitivePairs
     * @return
     * @throws MojoExecutionException
     */
    public int executeWithSensitiveArgsAndLogOutput(List<Pair<String, Boolean>> argAndIsSensitivePairs)
            throws MojoExecutionException {
        if (logger.isInfoEnabled()) {
            List<String> argsWithSensitiveArgsMasked = argAndIsSensitivePairs.stream()
                    .map(pair -> pair.getRight() ? "XXXX" : pair.getLeft()).collect(Collectors.toList());
            logger.info("Executing " + packageManagerCommand + " command: {} {}", packageManagerCommand,
                    StringUtils.join(argsWithSensitiveArgsMasked, " "));
        }
        ProcessExecutor executor = createPackageManagerExecutor(
                argAndIsSensitivePairs.stream().map(Pair::getLeft).collect(Collectors.toList()));
        return executor.executeAndRedirectOutput(logger);
    }

    /**
     * Executes a command with the given arguments and logs a warning message
     * if the command has not yet completed after the specified timeout period. This
     * may be useful for providing input to developers when certain commands
     * are running for longer than expected and may need to be manually halted due
     * to cache-related issues.<br>
     * <b>NOTE:</b>The executed command will *not* be halted nor terminated
     * when the timeout expires. After the timeout expires, this method will
     * continue to wait until underlying command completes.
     *
     * @param arguments
     * @param timeout
     * @param timeUnit
     * @return
     */
    public Integer executePackageManagerCommandAndLogAfterTimeout(List<String> arguments, int timeout, TimeUnit timeUnit, String messageToDisplay) {
        ExecutorService executor = Executors.newSingleThreadExecutor();
        Future<Integer> future = executor.submit(() -> this.executeAndLogOutput(arguments));
        try {
            return future.get(timeout, timeUnit);
        } catch (TimeoutException e) {
            logger.warn(packageManagerCommand + " " + String.join(" ", arguments)
                    + " has been running for quite some time, you may want to quit the mvn process (Ctrl+c) and run " + messageToDisplay + " and restart your build.");
            try {
                return future.get();
            } catch (InterruptedException | ExecutionException e1) {
                throw new RuntimeException("Error occurred while waiting for " + packageManagerCommand + " command to complete", e1);
            }
        } catch (Exception e) {
            throw new RuntimeException(String.format("Error occurred while performing " + packageManagerCommand + " command: " + packageManagerCommand + " %s",
                    StringUtils.join(arguments, " ")), e);
        } finally {
            executor.shutdown();
        }
    }

    protected ProcessExecutor createPackageManagerExecutor(List<String> arguments) {
        List<String> fullCommandArgs = new ArrayList<>();
        fullCommandArgs.add(packageManagerCommand);
        fullCommandArgs.addAll(arguments);
        return new ProcessExecutor(workingDirectory, fullCommandArgs, Platform.guess(), null);
    }

    protected ProcessExecutor createPackageManagerExecutor(List<String> arguments, Map<String, String> environmentVariables) {
        List<String> fullCommandArgs = new ArrayList<>();
        fullCommandArgs.add(packageManagerCommand);
        fullCommandArgs.addAll(arguments);
        return new ProcessExecutor(workingDirectory, fullCommandArgs, Platform.guess(), environmentVariables);
    }

}