package org.technologybrewery.habushu.exec;

import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.apache.commons.lang3.tuple.Pair;

public interface CommandHelper {

    /**
     * Executes a package manager command with the given arguments, logs the executed
     * command, and returns the resultant process output as a string. This method
     * should be utilized when performing downstream logic based on the output of a
     * command, or it is desirable to not show the command's generated
     * stdout.
     *
     * @param arguments list of arguments for commands
     * @return execution Result
     */
    String execute(List<String> arguments);

    /**
     * Executes a command with the given arguments, logs the executed
     * command, logs the stdout/stderr generated by the process, and returns the
     * process exit code. This method should be utilized when it is desirable to
     * immediately show all the stdout/stderr produced by a command for
     * diagnostic purposes.
     *
     * @param arguments list of arguments for commands
     * @return execution value
     */
    int executeAndLogOutput(List<String> arguments);

    /**
     * Executes a command with the given arguments and environment variables,
     * logs the executed command and logs the stdout/stderr generated by the process.
     * This method should be utilized when environment variables are needed for the command,
     * and it is desirable to immediately show all the stdout/stderr produced by a command for
     * diagnostic purposes.
     *
     * @param arguments list of arguments for commands
     * @param environmentVariables list of environment variable for the command
     */
    int executeAndLogOutput(List<String> arguments, Map<String, String> environmentVariables);

    /**
     * Similar to {@link #executeAndLogOutput(List)}, except the executed
     * command that is logged obfuscates/masks any given command arguments that are
     * marked as sensitive. This method should be utilized if any command
     * line arguments contain sensitive values that are not desirable to log, such
     * as passwords.
     *
     * @param argAndIsSensitivePairs list of args and their sensitivity
     * @return execution value
     */
    int executeWithSensitiveArgsAndLogOutput(List<Pair<String, Boolean>> argAndIsSensitivePairs);

    /**
     * Executes a command with the given arguments and logs a warning message
     * if the command has not yet completed after the specified timeout period. This
     * may be useful for providing input to developers when certain commands
     * are running for longer than expected and may need to be manually halted due
     * to cache-related issues.<br>
     * <b>NOTE:</b>The executed command will *not* be halted nor terminated
     * when the timeout expires. After the timeout expires, this method will
     * continue to wait until underlying command completes.
     *
     * @param arguments list of arguments for commands
     * @param timeout time durations
     * @param timeUnit granularity for the time durations
     * @param messageToDisplay message to display after timeout has occurred
     * @return executed results
     */
    Integer executeAndLogAfterTimeout(List<String> arguments, int timeout,
                                                                  TimeUnit timeUnit, String messageToDisplay);

    /**
     * Returns whether the specified dependency package is installed within this
     * project's virtual environment (and pyproject.toml).
     *
     * @param packageName the package name to check
     * @return whether the package is installed
     */
    boolean isDependencyInstalled(String packageName);

    /**
     * Installs the specified package as a development dependency to this
     * project's virtual environment and pyproject.toml specification.
     *
     * @param packageName the dependency to install
     */
    void installDevelopmentDependency(String packageName);

    /**
     * Reads the project name as seen by the package manager tool (i.e. pyproject.toml).
     *
     * @return the project name
     */
    String getProjectName();

    /**
     * Reads the project version as seen by the package manager tool (i.e. pyproject.toml).
     *
     * @return the project version
     */
    String getProjectVersion();
}
