package org.technologybrewery.habushu.exec;

import org.apache.commons.lang3.tuple.Pair;
import org.apache.maven.plugin.MojoExecutionException;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.concurrent.*;

/**
 * Facilitates the execution of PackageManager commands.
 */
public abstract class PackageManagerCommandHelper {

    public PackageManagerCommandHelper() {}

    /**
     * Returns a {@link String} indicating the relative path to the Package Manager
     * cache directory. This is equivalent to {@code package manager config cache-dir}.
     *
     * @return
     */
    public abstract String getPackageManagerCacheDirectoryPath() throws MojoExecutionException;

    /**
     * Returns whether the specified dependency package is installed within this
     * Poetry project's virtual environment (and pyproject.toml).
     *
     * @param packageName
     * @return
     */
    public abstract boolean isDependencyInstalled(String packageName);

    /**
     * Installs the specified package as a development dependency to this Package Manager
     * project's virtual environment and pyproject.toml specification.
     *
     * @param packageName
     */
    public void installDevelopmentDependency(String packageName) throws MojoExecutionException {
        execute(Arrays.asList("add", packageName, "--group", "dev"));
    }

    /**
     * Executes a Package Manager command with the given arguments, logs the executed
     * command, and returns the resultant process output as a string. This method
     * should be utilized when performing downstream logic based on the output of a
     * Package Manager command, or it is desirable to not show the command's generated
     * stdout.
     *
     * @param arguments
     * @return
     * @throws MojoExecutionException
     */
    public abstract String execute(List<String> arguments) throws MojoExecutionException;

    /**
     * Executes a Package Manager command with the given arguments, logs the executed
     * command, logs the stdout/stderr generated by the process, and returns the
     * process exit code. This method should be utilized when it is desirable to
     * immediately show all of the stdout/stderr produced by a Package Manager command for
     * diagnostic purposes.
     *
     * @param arguments
     * @return
     * @throws MojoExecutionException
     */
    public abstract int executeAndLogOutput(List<String> arguments) throws MojoExecutionException;

    /**
     * Executes a Package Manager command with the given arguments and environment variables,
     * logs the executed command and logs the stdout/stderr generated by the process.
     * This method should be utilized when environment variables are needed for the Package Manager command,
     * and it is desirable to immediately show all the stdout/stderr produced by a Package Manager command for
     * diagnostic purposes.
     *
     * @param arguments
     * @param environmentVariables
     */
    public abstract void executeAndLogOutput(List<String> arguments, Map<String, String> environmentVariables);

    /**
     * Similar to {@link #executeAndLogOutput(List)}, except the executed Package Manager
     * command that is logged obfuscates/masks any given command arguments that are
     * marked as sensitive. This method should be utilized if any Package Manager command
     * line arguments contain sensitive values that are not desirable to log, such
     * as passwords.
     *
     * @param argAndIsSensitivePairs
     * @return
     * @throws MojoExecutionException
     */
    public abstract int executeWithSensitiveArgsAndLogOutput(List<Pair<String, Boolean>> argAndIsSensitivePairs)
            throws MojoExecutionException;

    /**
     * Executes a Package Manager command with the given arguments and logs a warning message
     * if the command has not yet completed after the specified timeout period. This
     * may be useful for providing input to developers when certain Package Manager commands
     * are running for longer than expected and may need to be manually halted due
     * to cache-related issues.<br>
     * <b>NOTE:</b>The executed Package Manager command will *not* be halted nor terminated
     * when the timeout expires. After the timeout expires, this method will
     * continue to wait until underlying PackageManager command completes.
     *
     * @param arguments
     * @param timeout
     * @param timeUnit
     * @return
     */
    public abstract Integer executePackageManagerCommandAndLogAfterTimeout(List<String> arguments, int timeout, TimeUnit timeUnit);


    /**
     * Installs a PackageManager plugin with the given name.
     *
     * @param name
     * @return
     * @throws MojoExecutionException
     */
    public abstract int installPackageManagerPlugin(String name) throws MojoExecutionException;

    public List<String> createLockCommand() {
        return createLockCommand(true);
    }

    public abstract List<String> createLockCommand(boolean skipLockUpdate);

}