package org.technologybrewery.habushu.exec;

import org.apache.commons.lang3.StringUtils;
import org.apache.maven.plugin.MojoExecutionException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Facilitates the execution of UV commands.
 */
public class UVCommandHelper {

    private static final String UV_COMMAND = "uv";
    private static final String UV_TOOL_COMMAND = "uvx";
    private static final Logger logger = LoggerFactory.getLogger(UVCommandHelper.class);

    protected File workingDirectory;


    public UVCommandHelper(File workingDirectory) {
        this.workingDirectory = workingDirectory;
    }

    /**
     * Executes a UV command with the given arguments, logs the executed
     * command, and returns the resultant process output as a string. This method
     * should be utilized when performing downstream logic based on the output of a
     * UV command, or it is desirable to not show the command's generated
     * stdout.
     *
     * @param arguments list of arguments for uv commands
     * @return execution values
     */
    public String execute(List<String> arguments) {
        if (logger.isInfoEnabled()) {
            logger.info("Executing UV command: {} {}", UV_COMMAND, StringUtils.join(arguments, " "));
        }
        ProcessExecutor executor = createUVExecutor(arguments);
        return executor.executeAndGetResult(logger);
    }


    /**
     * Executes a UV Tool command with the given arguments, logs the executed
     * command, and returns the resultant process output as a string. This method
     * should be utilized when performing downstream logic based on the output of a
     * UV Tool command, or it is desirable to not show the command's generated
     * stdout.
     *
     * @param arguments list of arguments for uv commands
     * @return execution result
     */
    public String executeUVTool(List<String> arguments) {
        if (logger.isInfoEnabled()) {
            logger.info("Executing UV Tool command: {} {}", UV_TOOL_COMMAND, StringUtils.join(arguments, " "));
        }
        ProcessExecutor executor = createUVToolExecutor(arguments);
        return executor.executeAndGetResult(logger);
    }


    /**
     * Executes a UV command with the given arguments, logs the executed
     * command, logs the stdout/stderr generated by the process, and returns the
     * process exit code. This method should be utilized when it is desirable to
     * immediately show all of the stdout/stderr produced by a UV command for
     * diagnostic purposes.
     *
     * @param arguments list of arguments for uv commands
     * @return execution value
     */
    public int executeAndLogOutput(List<String> arguments) {
        if (logger.isInfoEnabled()) {
            logger.info("Executing UV command: {} {}", UV_COMMAND, StringUtils.join(arguments, " "));
        }
        ProcessExecutor executor = createUVExecutor(arguments);
        return executor.executeAndRedirectOutput(logger);
    }

    /**
     * Executes a UV tool command with the given arguments, logs the executed
     * command, logs the stdout/stderr generated by the process, and returns the
     * process exit code. This method should be utilized when it is desirable to
     * immediately show all of the stdout/stderr produced by a UV tool command for
     * diagnostic purposes.
     *
     * @param arguments list of arguments for uv commands
     * @return execution value
     */
    public int executeUVToolAndLogOutput(List<String> arguments) {
        if (logger.isInfoEnabled()) {
            logger.info("Executing UV Tool command: {} {}", UV_TOOL_COMMAND, StringUtils.join(arguments, " "));
        }
        ProcessExecutor executor = createUVToolExecutor(arguments);
        return executor.executeAndRedirectOutput(logger);
    }

    /**
     * Executes a UV command with the given arguments and environment variables,
     * logs the executed command and logs the stdout/stderr generated by the process.
     * This method should be utilized when environment variables are needed for the UV command,
     * and it is desirable to immediately show all the stdout/stderr produced by a UV command for
     * diagnostic purposes.
     *
     * @param arguments
     * @param environmentVariables
     */
    public void executeAndLogOutput(List<String> arguments, Map<String, String> environmentVariables) {
        if (logger.isInfoEnabled()) {
            logger.info("Executing UV command: {} {}", UV_COMMAND, StringUtils.join(arguments, " "));
        }
        ProcessExecutor executor = createUVExecutor(arguments, environmentVariables);
        executor.executeAndRedirectOutput(logger);
    }



    protected ProcessExecutor createUVExecutor(List<String> arguments) {
        List<String> fullCommandArgs = new ArrayList<>();
        fullCommandArgs.add(UV_COMMAND);
        fullCommandArgs.addAll(arguments);
        return new ProcessExecutor(workingDirectory, fullCommandArgs, Platform.guess(), null);
    }

    protected ProcessExecutor createUVToolExecutor(List<String> arguments) {
        List<String> fullCommandArgs = new ArrayList<>();
        fullCommandArgs.add(UV_TOOL_COMMAND);
        fullCommandArgs.addAll(arguments);
        return new ProcessExecutor(workingDirectory, fullCommandArgs, Platform.guess(), null);
    }

    protected ProcessExecutor createUVExecutor(List<String> arguments, Map<String, String> environmentVariables) {
        List<String> fullCommandArgs = new ArrayList<>();
        fullCommandArgs.add(UV_COMMAND);
        fullCommandArgs.addAll(arguments);
        return new ProcessExecutor(workingDirectory, fullCommandArgs, Platform.guess(), environmentVariables);
    }

    public List<String> createLockCommand() {
        List<String> arguments = new ArrayList<>();
        arguments.add("lock");

        return arguments;
    }
    
}