[[tool.pdm.source]]
name = "dev-pypi"
url = "https://test.pypi.org/simple/"
verify_ssl = true

[project]
authors = [
    {name = "James Choi", email = "choi_james@bah.com"},
]
license = {text = "MIT License"}
requires-python = "<4.0,>=3.11"
dependencies = [
    "krausening==19",
    "cryptography<43.0.0,>=42.0.0",
    "uvicorn[standard]<1.0.0,>=0.18.0",
]
name = "habushu_mixology_uv"
version = "2.18.0.dev"
description = "Example of how to use the habushu-maven-plugin in a `uv`-based setting"

[dependency-groups]
dev = [
    "behave>=1.2.6",
    "pylint>=3.1.0",
    "black>=24.3.0",
    "python-dotenv<1.0.0,>=0.20.0",
    "grpcio-tools<2.0.0,>=1.48.0",
    "kappa-maki>=1.0.0",
]
