[project]
name = "habushu_poetry_containerize"
version = "3.0.0.dev"
description = "Example of how to use the habushu-maven-plugin to containerize an application"
authors = [{name = "Isaac Becerra Llanos", email = "ibecerrallanos@cpointe-inc.com"}]
license = "MIT License"
requires-python = ">=3.12"
dynamic = ["version", "dependencies"]

[tool.poetry.dependencies]

[tool.poetry.group.dev.dependencies]
ruff = ">=0.9.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
indent-width = 4

[tool.ruff.format]
indent-style="space"
line-ending="lf"
quote-style="preserve"


# Added by habushu-maven-plugin at 2025-03-12T16:30:58.712573 to use https://test.pypi.org/simple/ as source PyPi repository for installing dependencies
[[tool.poetry.source]]
name = "dev-pypi"
url = "https://test.pypi.org/simple/"
priority = "supplemental"
