[project]
name = "habushu-uv-add-to-project"
version = "3.0.0.dev"
description = "This example demonstrates how to add Habushu to a new or existing uv project."
readme = "README.md"
authors = [
    { name = "Margaret Black", email = "black_margaret@bah.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ruff>=0.9.9",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff.format]
indent-style="space"
line-ending="lf"
quote-style="preserve"

[tool.ruff.lint]
ignore = ["E4","E7","F"]

[dependency-groups]
dev = [
    "behave>=1.2.6",
    "kappa-maki>=1.0.2",
]

# Added by habushu-maven-plugin at 2025-04-09T14:26:42.416126 to use https://pypi.org/simple/ as source repository for installing dependencies
[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple/"
publish-url = "https://pypi.org/simple/"
