[project]
name = "habushu-uv-pytest"
version = "3.4.1"
description = "Example of how to use Habushu for pytest testing"
readme = "README.md"
authors = [
    {name = "Chaoyi Sun", email = "csun@cpointe-inc.com"},
]
requires-python = ">=3.12"

[tool.uv]
# habushu will detect the pytest dependency for test package
dev-dependencies = [
    "pytest>=8.3.3",
]

# Register custom marks in your pyproject.toml file
[tool.pytest.ini_options]
markers = [
    "integration_test: marks tests as integration tests",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# Added by habushu-maven-plugin at 2025-06-03T09:24:57.101831 to use https://pypi.org/simple/ as source repository for installing dependencies
[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple/"
publish-url = "https://pypi.org/simple/"

[dependency-groups]
dev = [
    "ruff>=0.11.12",
]
