<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.technologybrewery.habushu</groupId>
        <artifactId>habushu</artifactId>
        <version>3.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>examples</artifactId>
    <packaging>pom</packaging>

    <name>habushu::Examples</name>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.technologybrewery.habushu</groupId>
                    <artifactId>habushu-maven-plugin</artifactId>
                    <!-- Since we're working in the habushu repo, we must set the project version dynamically -->
                    <!-- Outside of this repo, the version should be hardcoded here or in the parent pom -->
                    <version>${project.version}</version>
                    <!-- This configuration allows Habushu to extend/customize the Maven build lifecyle,
                    which is required for the plugin to function -->
                    <extensions>true</extensions>
                    <configuration>
                        <pythonVersion>${version.python.default}</pythonVersion>
                        <!-- Skips any scenarios tagged with @integration-test - these will
                            be executed via the "integration-test" Maven profile -->
                        <behaveOptions>--tags ~integration_test</behaveOptions>
                        <useDevRepository>true</useDevRepository>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <dependencies>
                        <dependency>
                            <groupId>org.technologybrewery.habushu</groupId>
                            <artifactId>habushu-maven-plugin</artifactId>
                            <version>${project.version}</version>
                        </dependency>
                    </dependencies>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>net.masterthought</groupId>
                <artifactId>cucumber-reporting</artifactId>
                <version>${version.cucumber.reporting}</version>
                <scope>test</scope>
            </dependency>
            <!-- NB: workaround to trigger build cache invalidation when a new SNAPSHOT is available-->
            <!-- This dependency is required specifically to build the examples in this repo -->
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>habushu-maven-plugin</artifactId>
                <version>${project.version}</version>
                <scope>provided</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <profiles>
        <profile>
            <id>default</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <modules>
                <module>poetry</module>
                <module>uv</module>
                <module>add-habushu-to-new-or-existing-poetry-project</module>
                <module>habushu-managed-dependencies</module>
                <module>habushu-default-python-strategy</module>
                <module>habushu-running-python-scripts</module>
                <module>habushu-containerize</module>
            </modules>
        </profile>
        <profile>
            <id>uv</id>
            <modules>
                <module>add-habushu-to-new-or-existing-uv-project</module>
                <module>habushu-export-requirements-with-path-dependencies</module>
                <module>habushu-uv-package</module>
                <module>habushu-uv-devrepository-package</module>
                <module>habushu-containerize</module>
            </modules>
        </profile>
    </profiles>

</project>
