<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.technologybrewery.habushu</groupId>
        <artifactId>habushu</artifactId>
        <version>2.18.0-SNAPSHOT</version>
    </parent>

    <artifactId>examples</artifactId>
    <packaging>pom</packaging>

    <name>habushu::Examples</name>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.technologybrewery.habushu</groupId>
                    <artifactId>habushu-maven-plugin</artifactId>
                    <version>${project.version}</version>
                    <extensions>true</extensions>
                    <configuration>
                        <pythonVersion>${version.python.default}</pythonVersion>
                        <!-- Skips any scenarios tagged with @integration-test - these will
                            be executed via the "integration-test" Maven profile -->
                        <behaveOptions>--tags ~integration_test</behaveOptions>
                        <useDevRepository>true</useDevRepository>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>net.masterthought</groupId>
                <artifactId>cucumber-reporting</artifactId>
                <version>${version.cucumber.reporting}</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <profiles>
        <profile>
            <id>default</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <modules>
                <module>habushu-poetry-package</module>
                <module>habushu-poetry-package-consumer</module>
                <module>habushu-managed-dependencies</module>
            </modules>
        </profile>
        <profile>
            <id>uv</id>
            <modules>
                <module>habushu-uv-package</module>
            </modules>
        </profile>
    </profiles>

</project>