<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.technologybrewery.habushu</groupId>
        <artifactId>poetry</artifactId>
        <version>3.1.0-SNAPSHOT</version>
    </parent>

    <name>habushu::Examples::Poetry::Dependency Groups</name>
    <description>Example of how to use the dependency group related habushu-maven-plugin configurations with Poetry</description>

    <artifactId>habushu-poetry-dependency-groups</artifactId>
    <packaging>habushu</packaging>

    <build>
        <directory>dist</directory>
        <plugins>
            <plugin>
                <groupId>org.technologybrewery.habushu</groupId>
                <artifactId>habushu-maven-plugin</artifactId>
                <configuration>
                    <forceSync>true</forceSync>
                    <withGroups>
                        <group>groupA</group>
                    </withGroups>
                    <withoutGroups>
                        <group>groupB</group>
                    </withoutGroups>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>