[project]
name = "habushu_uv_package"
version = "3.2.0"
description = "Example of how to use the habushu-maven-plugin in a uv-based setting"
readme = "README.md"
authors = [
    {name = "James Choi", email = "choi_james@bah.com"},
]
license = {text = "MIT License"}
requires-python = ">=3.12"
dependencies = [
    "krausening>=20",
    "cryptography>=44.0.1",
    "uvicorn[standard]>=0.19.0",
]

[dependency-groups]
dev = [
    "behave>=1.2.6",
    "ruff>=0.9.9",
    "python-dotenv<1.0.0,>=0.20.0",
    "grpcio-tools>=1.48.0",
    "kappa-maki>=1.0.0",
    "ruff>=0.9.9",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# Added by habushu-maven-plugin at 2025-04-09T09:49:04.175061 to use https://pypi.org/simple/ as source repository for installing dependencies
[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple/"
publish-url = "https://pypi.org/simple/"
