<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.technologybrewery.habushu</groupId>
        <artifactId>poetry</artifactId>
        <version>3.3.0-SNAPSHOT</version>
    </parent>

    <name>habushu::Examples::Poetry::Build a Package</name>
    <description>Example of how to use the habushu-maven-plugin with Poetry</description>

    <artifactId>habushu-poetry-package</artifactId>
    <packaging>habushu</packaging>

    <build>
        <directory>dist</directory>
    </build>

    <profiles>
        <profile>
            <id>integration-test</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.technologybrewery.habushu</groupId>
                        <artifactId>habushu-maven-plugin</artifactId>
                        <configuration>
                            <!-- Demonstrates how different sets of environment variables may
                                be injected into the virtual environment when executing tests through behave -->
                            <behaveOptions>-Denvironment=integration_test --tags integration_test</behaveOptions>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
