[tool.poetry]

[project]
name = "habushu_default_python_strategy"
version = "3.0.0.dev"
description = "Example of how to use the habushu default python strategy configuration"
authors = [{name = "Ryan Ashcraft", email = "ryan.ashcraft@codifyiq.com"}]
license = "MIT License"
requires-python = ">=3.11"
dynamic = ["version", "dependencies"]

[tool.poetry.dependencies]

[tool.poetry.group.dev.dependencies]
behave = ">=1.2.6"
kappa-maki = ">=1.0.0"
ruff = ">=0.9.9"

[build-system]
requires = ["poetry-core>=1.6.0"]
build-backend = "poetry.core.masonry.api"

# Added by habushu-maven-plugin at 2024-05-06T17:43:13.504546 to use https://test.pypi.org/simple/ as source PyPi repository for installing dependencies
[[tool.poetry.source]]
name = "dev-pypi"
url = "https://test.pypi.org/simple/"
priority = "supplemental"

[tool.ruff.format]
indent-style="space"
line-ending="lf"
quote-style="preserve"

[tool.ruff.lint]
ignore = ["E4","E7","F"]