[project]
name = "habushu_default_python_strategy"
version = "3.0.0"
description = "Example of how to use the habushu default python strategy configuration"
authors = [{name = "Ryan Ashcraft", email = "ryan.ashcraft@codifyiq.com"}]
license = "MIT License"
requires-python = ">=3.12"
dynamic = ["version", "dependencies"]

[tool.poetry.group.dev.dependencies]
behave = ">=1.2.6"
kappa-maki = ">=1.0.0"
ruff = ">=0.9.9"

[build-system]
requires = ["poetry-core>=1.6.0"]
build-backend = "poetry.core.masonry.api"