[project]
name = "habushu_poetry_containerize"
version = "3.0.0.dev"
description = "Example of how to use the habushu-maven-plugin to containerize an application"
authors = [{name = "Isaac Becerra Llanos", email = "ibecerrallanos@cpointe-inc.com"}]
license = "MIT License"
requires-python = ">=3.12"
dynamic = ["version", "dependencies"]

[tool.poetry.group.dev.dependencies]
ruff = ">=0.9.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"