<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.technologybrewery.habushu</groupId>
        <artifactId>uv</artifactId>
        <version>3.4.1</version>
    </parent>

    <name>habushu::Examples::uv Enforcer Rule</name>
    <description>Example of how to use Habushu's Maven Enforcer Rule for validating uv versions</description>

    <artifactId>habushu-uv-enforcer-rule</artifactId>
    <packaging>pom</packaging>

    <build>
        <directory>dist</directory>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <executions>
                    <!--
                        NB: this is also set up in the examples pom, but we are overriding it here to explicitly provide
                        a concrete example of how it is configured.
                     -->
                    <execution>
                        <id>enforce-uv</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <requireUvVersion>
                                    <version>>=0.6.0</version>
                                </requireUvVersion>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.technologybrewery.habushu</groupId>
                        <artifactId>habushu-maven-plugin</artifactId>
                        <version>${project.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>

</project>
