FROM $builderBaseImage AS habushu_builder

# Install pipx
RUN python -m ensurepip --upgrade
RUN python -m pip install --user pipx

# Poetry and supporting plugin installations
RUN $HOME/.local/bin/pipx install poetry==$poetryVersion && \
    $HOME/.local/bin/poetry self add poetry-plugin-bundle@$poetryPluginBundleVersion

WORKDIR /work-dir
COPY $chownPlaceholder $anchorDirectory ./containerize-support/
RUN find . -type f -name pyproject.toml -exec sed -i 's|develop[[:blank:]]*=[[:blank:]]*true|develop = false|g' {} \;

USER root
WORKDIR /work-dir/containerize-support/$singleRepoProjectDir
ENV POETRY_CACHE_DIR="/.cache/pypoetry"

# Export target project's virtual environment to /opt/venv
RUN --mount=type=cache,target=${POETRY_CACHE_DIR} \
    $HOME/.local/bin/poetry lock && \
    $HOME/.local/bin/poetry bundle venv /opt/venv