FROM $baseImage AS final

# Copy venv from builder and activate by adding to the path
COPY --from=habushu_builder $chownPlaceholder \
    /work-dir/containerize-support/$singleRepoProjectDir/.venv \
    /opt/venv/
ENV PATH="/opt/venv/bin:$PATH"