FROM $baseImage AS habushu_builder

# uv installation
COPY --from=ghcr.io/astral-sh/uv:$uvVersion /uv /uvx /bin/

WORKDIR /work-dir
COPY $chownPlaceholder $anchorDirectory ./containerize-support/

USER root
WORKDIR /work-dir/containerize-support/$singleRepoProjectDir

# Sync the target project into the containerized environment
RUN uv sync --frozen --no-editable --no-dev