package org.technologybrewery.habushu;

import java.time.format.DateTimeFormatter;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.technologybrewery.habushu.util.HabushuUtil;
import org.technologybrewery.habushu.util.PackageManager;

/**
 * Publishes the distribution archives generated by
 * {@link BuildDeploymentArtifactsMojo} to the configured PyPI repository.
 * {@link PublishToPyPiRepoMojo} leverages Poetry/UV to support publishing to
 * private PyPI repositories as well as the official PyPI repository.
 * <p>
 * If publishing to a private PyPI repository, both {@link #pypiRepoId} and
 * {@link #pypiRepoUrl} <b>MUST</b> be specified, and it is expected that the
 * relevant username/password credentials are configured in a settings.xml
 * {@literal <server>} entry that has an {@literal <id>} that aligns with the
 * provided {@link #pypiRepoId}.
 * <p>
 * If neither {@link #pypiRepoId} nor {@link #pypiRepoUrl} are provided, *OR*
 * {@link #pypiRepoId} is set to {@code pypi} and {@link #pypiRepoUrl} is not
 * provided, it is assumed that the archives will be published to the official
 * PyPI repository. As described above, developers are expected to provide their
 * PyPI credentials via a username/password entry in their settings.xml with an
 * {@code <id>} that matches {@code pypi}, or use the appropriate Poetry command
 * to configure their PyPI credentials in an adhoc fashion (i.e.
 * {@code poetry config pypi-token.pypi my-token}).
 * <p>
 * If the POM version of the module being published is a SNAPSHOT, the Poetry
 * package will be published to the configured PyPI repository as a Python
 * developmental release. Developers may use
 * {@link #snapshotNumberDateFormatPattern} to adjust the formatting of the
 * numeric component of the published version.
 */
@Mojo(name = "publish-to-pypi-repo", defaultPhase = LifecyclePhase.DEPLOY, threadSafe = true)
public class PublishToPyPiRepoMojo extends AbstractHabushuMojo {

    /**
     * {@link DateTimeFormatter} compliant pattern that configures the numeric
     * portion of SNAPSHOT Poetry package versions that are published to the
     * configured PyPI repository. By default, the version of SNAPSHOT published
     * packages align with PEP-440 developmental releases and use a numeric
     * component that corresponds to the number of seconds since the epoch. For
     * example, if the POM version is {@code 1.2.3-SNAPSHOT}, the package may be
     * published by default as {@code 1.2.3.dev1658238063}. If
     * {@link #snapshotNumberDateFormatPattern} is provided, the numeric component
     * will reflect the given date format pattern applied to the current build time.
     * For example, if "YYYYMMddHHmm" is provided, {@code 1.2.3.dev202207191002} may
     * be published.
     */
    @Parameter(property = "habushu.snapshotNumberDateFormatPattern")
    protected String snapshotNumberDateFormatPattern;

    /**
     * Skips the entire execution of the deploy phase and does *not* publish the
     * Poetry package to the configured PyPI repository. This configuration may be
     * useful when individual Habushu modules within a larger multi-module project
     * hierarchy should *not* be published to PyPI, but it is still desirable to
     * automate the project's release via the {@code maven-release-plugin}.
     */
    @Parameter(property = "habushu.skipDeploy", defaultValue = "false")
    protected boolean skipDeploy;

    /**
     * Specifies the number of times a push to the configured PyPI repository will be attempted before stopping (inclusive
     * of the initial attempt). While this defaults to three and is fully configurable, it can be set to zero to never
     * retry or set to any negative number for unlimited retries.  Unlimited retries will follow a fibonacci backoff
     * interval.
     */
    @Parameter(property = "habushu.pyPiPushRetries", defaultValue = "3")
    protected int pypiPushRetries = 3;

    /**
     * A multiplier, in milliseconds, to apply to the retry wait time (e.g., round of fibonacci).
     */
    @Parameter(property = "habushu.pypiPushRetryMultiplier", defaultValue = "15000")
    protected long pypiPushRetryMultiplier;

    /**
     * Maximum time to wait for a retry, in minutes, even if the backoff algorithm is above this threshold.
     */
    @Parameter(property = "habushu.pypiPushRetryMaxTimeout", defaultValue = "3")
    protected long pypiPushRetryMaxTimeout;

    @Override
    public void doExecute() throws MojoExecutionException, MojoFailureException {
        if (this.skipDeploy) {
            getLog().info(String.format(
                    "Skipping deploy phase - package for %s will not be published to the configured PyPI repository",
                    this.project.getId()));
            return;
        }

        if (HabushuUtil.checkPythonPackageManager(getPyProjectTomlFile()) == PackageManager.POETRY) {
            PublishToPyPiRepoPoetry publishToPyPiRepoPoetry = new PublishToPyPiRepoPoetry(getPythonProjectBaseDir(), getLog(), this);
            publishToPyPiRepoPoetry.doExecute();
        } else {
            PublishToPyPiRepoUv publishToPyPiRepoUv = new PublishToPyPiRepoUv(getPythonProjectBaseDir(), getLog(), this);
            publishToPyPiRepoUv.doExecute();
        }
    }


    public String getSnapshotNumberDateFormatPattern() {
        return snapshotNumberDateFormatPattern;
    }

    public boolean skipDeploy() {
        return skipDeploy;
    }

    public String getPypiUploadSuffix() {
        return pypiUploadSuffix;
    }

    public String getDevRepositoryUrlUploadSuffix() {
        return devRepositoryUrlUploadSuffix;
    }

    public int getPypiPushRetries() {
        return pypiPushRetries;
    }

    public long getPypiPushRetryMultiplier() {
        return pypiPushRetryMultiplier;
    }

    public long getPypiPushRetryMaxTimeout() {
        return pypiPushRetryMaxTimeout;
    }

    public boolean enableDevRepositoryUrlUploadSuffix() {
        return enableDevRepositoryUrlUploadSuffix;
    }


}
