package org.technologybrewery.habushu;

import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.tuple.ImmutablePair;
import org.apache.commons.lang3.tuple.Pair;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.plugin.logging.Log;
import org.technologybrewery.habushu.exec.PoetryCommandHelper;
import org.technologybrewery.habushu.util.HabushuUtil;

import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * Publishes the distribution archives generated by
 * {@link BuildDeploymentArtifactsMojo} to the configured PyPI repository.
 * {@link PublishToPyPiRepoPoetry} leverages Poetry to support publishing to
 * private PyPI repositories as well as the official PyPI repository.
 * <p>
 */
public class PublishToPyPiRepoPoetry extends AbstractPublishToPyPiRepo {

    private static final String VERSION = "version";

    /**
     * New instance - these values are typically passed in from Maven-enabled parameters in the calling Mojo.
     *
     * @param baseDir base directory from which to operate for this module
     * @param log     the logger to use for output
     * @param mojo    Configurations for BuildDeploymentArtifactsMojo
     */
    protected PublishToPyPiRepoPoetry(File baseDir, Log log, PublishToPyPiRepoMojo mojo) {
        super(baseDir, log, mojo);
    }


    @Override
    public void doExecute() throws MojoExecutionException, MojoFailureException {
        PoetryCommandHelper poetryHelper = new PoetryCommandHelper(baseDir);

        String pomVersion = publishToPyPiRepoMojo.getProject().getVersion();
        if (publishToPyPiRepoMojo.overridePackageVersion() && HabushuUtil.isPomVersionSnapshot(pomVersion)) {
            String currentPythonPackageVersion = poetryHelper.execute(Arrays.asList(VERSION, "-s"));

            String snapshotVersionToPublish = HabushuUtil.getPythonPackageVersion(pomVersion, true,
                    publishToPyPiRepoMojo.getSnapshotNumberDateFormatPattern());
            try {
                log.info(
                        String.format("Setting version of Poetry package to publish to %s", snapshotVersionToPublish));
                poetryHelper.executeAndLogOutput(Arrays.asList(VERSION, snapshotVersionToPublish));
                publishPackage(poetryHelper, true);
            } finally {
                log.info(
                        String.format("Resetting Poetry package version back to %s", currentPythonPackageVersion));
                poetryHelper.executeAndLogOutput(Arrays.asList(VERSION, currentPythonPackageVersion));
            }

        } else {
            publishPackage(poetryHelper, false);
        }

    }

    /**
     * Helper method that encapsulates publishing the Poetry package to the
     * configured PyPI repository.
     *
     * @param poetryHelper   Poetry command helper that delegates publishing
     *                       commands to Poetry.
     * @param rebuildPackage whether to rebuild the package prior to publishing it.
     *                       This is typically only required for SNAPSHOT packages
     *                       where the version of the Poetry package may be
     *                       dynamically set in
     *                       {@link PublishToPyPiRepoPoetry()} and as a
     *                       result, the artifacts that were built by previously
     *                       executed build phase (i.e.
     *                       {@link BuildDeploymentArtifactsMojo}) do not reference
     *                       a version that aligns with the target version to be
     *                       published.
     * @throws MojoExecutionException
     */
    protected void publishPackage(PoetryCommandHelper poetryHelper, boolean rebuildPackage)
            throws MojoExecutionException {

        boolean publishToDev = checkPublishToDev(rebuildPackage);

        String username = null;
        String password = null;
        String repoId = publishToDev ? publishToPyPiRepoMojo.getDevRepositoryId() : publishToPyPiRepoMojo.getPypiRepoId();
        if (StringUtils.isNotEmpty(repoId)) {
            username = publishToPyPiRepoMojo.findUsernameForServer(repoId);
            password = publishToPyPiRepoMojo.findPasswordForServer(repoId);
        }

        String repoUrl = getRepositoryUrl(publishToDev);
        if (StringUtils.isNotEmpty(repoUrl)) {
            if (StringUtils.isEmpty(username) || StringUtils.isEmpty(password)) {
                throw new MojoExecutionException(String.format(
                        "Please ensure that both <username> and <password> are provided for the <server> with <id> %s in your settings.xml configuration!",
                        repoId));
            }

            log.info(String.format("Adding repository configuration to poetry.toml for %s at %s", repoId,
                    repoUrl));
            poetryHelper.execute(
                    Arrays.asList("config", "--local", String.format("repositories.%s", repoId), repoUrl));
        }

        List<Pair<String, Boolean>> publishToRepoWithCredsArgs = Collections.emptyList();

        if (StringUtils.isNotEmpty(username) && StringUtils.isNotEmpty(password)) {

            publishToRepoWithCredsArgs = new ArrayList<>();

            if (!HabushuUtil.PUBLIC_PYPI_REPO_ID.equals(repoId)) {
                publishToRepoWithCredsArgs.add(new ImmutablePair<>("--repository", false));
                publishToRepoWithCredsArgs.add(new ImmutablePair<>(repoId, false));
            }
            publishToRepoWithCredsArgs.add(new ImmutablePair<>("--username", false));
            publishToRepoWithCredsArgs.add(new ImmutablePair<>(username, false));
            publishToRepoWithCredsArgs.add(new ImmutablePair<>("--password", false));
            publishToRepoWithCredsArgs.add(new ImmutablePair<>(password, true));
        }

        String publishCommand = publishToPyPiRepoMojo.rewriteLocalPathDepsInArchives() ? "publish-rewrite-path-deps" : "publish";

        log.info(String.format("Publishing archives to %s %s",
                StringUtils.isNotEmpty(repoUrl) ? repoUrl : "official PyPI repository",
                publishToPyPiRepoMojo.rewriteLocalPathDepsInArchives() ? "with poetry-monorepo-dependency-plugin" : ""));

        if (!publishToRepoWithCredsArgs.isEmpty()) {
            publishToRepoWithCredsArgs.add(0, new ImmutablePair<>(publishCommand, false));
            if (rebuildPackage) {
                publishToRepoWithCredsArgs.add(1, new ImmutablePair<>("--build", false));
            }

        } else {
            log.warn(String.format(
                    "PyPI repository credentials not specified in <server> element in settings.xml with <id> of %s",
                    HabushuUtil.PUBLIC_PYPI_REPO_ID));
            log.warn(
                    "Please populate settings.xml with PyPI credentials or ensure that Poetry is manually " +
                            "configured with the correct PyPI credentials (i.e. poetry config pypi-token.pypi my-token)");
            publishToRepoWithCredsArgs.add(new ImmutablePair<>(publishCommand, false));
            if (rebuildPackage) {
                publishToRepoWithCredsArgs.add(new ImmutablePair<>("--build", false));
            }
        }

        invokePublish(poetryHelper, publishToRepoWithCredsArgs);
    }

}
