package org.technologybrewery.habushu;

import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.tuple.ImmutablePair;
import org.apache.commons.lang3.tuple.Pair;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.plugin.logging.Log;
import org.technologybrewery.habushu.exec.UvCommandHelper;
import org.technologybrewery.habushu.util.HabushuUtil;
import org.technologybrewery.habushu.util.PythonRepository;

import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * Publishes the distribution archives generated by
 * {@link BuildDeploymentArtifactsMojo} to the configured PyPI repository.
 * {@link PublishToPyPiRepoUv} leverages Poetry to support publishing to
 * private PyPI repositories as well as the official PyPI repository.
 * <p>
 */
public class PublishToPyPiRepoUv extends AbstractPublishToPyPiRepo {

    /**
     * New instance - these values are typically passed in from Maven-enabled parameters in the calling Mojo.
     *
     * @param baseDir base directory from which to operate for this module
     * @param log     the logger to use for output
     * @param mojo    Configurations for BuildDeploymentArtifactsMojo
     */
    protected PublishToPyPiRepoUv(File baseDir, Log log, PublishToPyPiRepoMojo mojo) {
        super(baseDir, log, mojo);
    }


    @Override
    public void doExecute() throws MojoExecutionException, MojoFailureException {

        UvCommandHelper uvCommandHelper = new UvCommandHelper(baseDir);

        String pomVersion = publishToPyPiRepoMojo.getProject().getVersion();
        if (publishToPyPiRepoMojo.overridePackageVersion() && HabushuUtil.isPomVersionSnapshot(pomVersion)) {

            List<String> getPythonProjectVersion = Arrays.asList("--from=toml-cli", "toml", "get", "--toml-path=pyproject.toml", "project.version");
            List<String> getPythonProjectVersionCommamd = uvCommandHelper.createToolRunCommand(getPythonProjectVersion);
            String currentPythonPackageVersion = uvCommandHelper.execute(getPythonProjectVersionCommamd);

            String snapshotVersionToPublish = HabushuUtil.getPythonPackageVersion(pomVersion, true,
                    publishToPyPiRepoMojo.getSnapshotNumberDateFormatPattern());
            try {
                log.info(
                        String.format("Setting version of UV package to publish to %s", snapshotVersionToPublish));
                List<String> setPythonProjectVersion = Arrays.asList("--from=toml-cli", "toml", "set", "--toml-path=pyproject.toml", "project.version", snapshotVersionToPublish);
                List<String> setPythonProjectVersionCommand = uvCommandHelper.createToolRunCommand(setPythonProjectVersion);
                uvCommandHelper.executeAndLogOutput(setPythonProjectVersionCommand);
                publishPackage(uvCommandHelper, true, snapshotVersionToPublish);
            } finally {
                log.info(
                        String.format("Resetting UV package version back to %s", currentPythonPackageVersion));
                List<String> setPythonProjectVersion = Arrays.asList("--from=toml-cli", "toml", "set", "--toml-path=pyproject.toml", "project.version", currentPythonPackageVersion);
                List<String> setPythonProjectVersionCommand = uvCommandHelper.createToolRunCommand(setPythonProjectVersion);
                uvCommandHelper.executeAndLogOutput(setPythonProjectVersionCommand);
            }

        } else {
            // Convert to PEP-440 format for glob pattern matching (e.g., 1.5.0-RC2 -> 1.5.0rc2)
            String pythonVersion = HabushuUtil.getPythonPackageVersion(pomVersion, false, null);
            publishPackage(uvCommandHelper, false, pythonVersion);
        }

    }

    /**
     * Helper method that encapsulates publishing the Poetry package to the
     * configured PyPI repository.
     *
     * @param uvCommandHelper   UV command helper that delegates publishing
     *                       commands to UV.
     * @param rebuildPackage whether to rebuild the package prior to publishing it.
     *                       This is typically only required for SNAPSHOT packages
     *                       where the version of the UV package may be
     *                       dynamically set in
     *                       {@link PublishToPyPiRepoUv ()} and as a
     *                       result, the artifacts that were built by previously
     *                       executed build phase (i.e.
     *                       {@link BuildDeploymentArtifactsMojo}) do not reference
     *                       a version that aligns with the target version to be
     *                       published.
     * @throws MojoExecutionException
     */
    protected void publishPackage(UvCommandHelper uvCommandHelper, boolean rebuildPackage, String version)
            throws MojoExecutionException {

        boolean publishToDev = checkPublishToDev(rebuildPackage);

        String username = null;
        String password = null;
        String repoId = publishToDev ? publishToPyPiRepoMojo.getDevRepositoryId() : publishToPyPiRepoMojo.getPypiRepoId();
        if (StringUtils.isNotEmpty(repoId)) {
            username = publishToPyPiRepoMojo.findUsernameForServer(repoId);
            password = publishToPyPiRepoMojo.findPasswordForServer(repoId);
        }

        String repoUrl = getRepositoryUrl(publishToDev);
        if (StringUtils.isNotEmpty(repoUrl) && (StringUtils.isEmpty(username) || StringUtils.isEmpty(password))) {
            throw new MojoExecutionException(String.format(
                    "Please ensure that both <username> and <password> are provided for the <server> with <id> %s in your settings.xml configuration!",
                    repoId));
        }

        List<Pair<String, Boolean>> publishToRepoWithCredsArgs = Collections.emptyList();

        if (StringUtils.isNotEmpty(username) && StringUtils.isNotEmpty(password)) {

            publishToRepoWithCredsArgs = new ArrayList<>();

            //Need to specify specific files as by default it would publish all tar.gz and whl files in dist folder.
            //When publishing locally, uv will throw error if file name is same but hash is different which fails case of -dev0 https://github.com/astral-sh/uv/issues/7917#issuecomment-2495160227
            publishToRepoWithCredsArgs.add(new ImmutablePair<>("./dist/*" + version + "*.tar.gz" , false));
            publishToRepoWithCredsArgs.add(new ImmutablePair<>("./dist/*" + version + "*.whl" , false));
            if (!PythonRepository.PUBLIC_PYPI_REPO_ID.equals(repoId)) {
                publishToRepoWithCredsArgs.add(new ImmutablePair<>("--index", false));
                publishToRepoWithCredsArgs.add(new ImmutablePair<>(repoId, false));
            }
            publishToRepoWithCredsArgs.add(new ImmutablePair<>("--username", false));
            publishToRepoWithCredsArgs.add(new ImmutablePair<>(username, false));
            publishToRepoWithCredsArgs.add(new ImmutablePair<>("--password", false));
            publishToRepoWithCredsArgs.add(new ImmutablePair<>(password, true));
        }

        String publishCommand = "publish";

        log.info(String.format("Publishing archives to %s",
                StringUtils.isNotEmpty(repoUrl) ? repoUrl : "official PyPI repository"));

        if (!publishToRepoWithCredsArgs.isEmpty()) {
            publishToRepoWithCredsArgs.add(0, new ImmutablePair<>(publishCommand, false));
            if (rebuildPackage) {
                log.info("Rebuilding uv before publishing PyPi repository...");
                if (publishToPyPiRepoMojo.isRewriteLocalPathDepsInArchives()) {
                    List<String> buildCommand = new ArrayList<>();
                    buildCommand.add("uv-monorepo-dependency-tool");
                    buildCommand.add("build-rewrite-path-deps");
                    log.info("Building source and wheel archives with uv-monorepo-dependency-tool...");
                    uvCommandHelper.executeAndLogOutput(uvCommandHelper.createToolRunCommand(buildCommand));
                } else {
                    log.info("Building source and wheel archives...");
                    uvCommandHelper.executeAndLogOutput(Arrays.asList("build"));
                }

            }
        } else {
            log.warn(String.format(
                    "PyPI repository credentials not specified in <server> element in settings.xml with <id> of %s",
                    PythonRepository.PUBLIC_PYPI_REPO_ID));
            log.warn(
                    "Please populate settings.xml with PyPI credentials or ensure that Poetry is manually " +
                            "configured with the correct PyPI credentials (i.e. poetry config pypi-token.pypi my-token)");
            publishToRepoWithCredsArgs.add(new ImmutablePair<>(publishCommand, false));
            if (rebuildPackage) {
                log.info("rebuilding uv before publishing PyPi repository...");
                String buildCommand = "build";
                uvCommandHelper.executeAndLogOutput(Arrays.asList(buildCommand));
            }
        }

        invokePublish(uvCommandHelper, publishToRepoWithCredsArgs);
    }

}
