<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.technologybrewery.habushu</groupId>
        <artifactId>examples</artifactId>
        <version>3.4.0-SNAPSHOT</version>
    </parent>

    <name>habushu::Examples::Managed Dependencies</name>
    <description>Example of how to use habushu to manage dependency versions across modules</description>

    <artifactId>habushu-managed-dependencies</artifactId>
    <packaging>habushu</packaging>

    <build>
        <directory>dist</directory>
        <plugins>
            <plugin>
                <groupId>org.technologybrewery.habushu</groupId>
                <artifactId>habushu-maven-plugin</artifactId>
                <configuration>
                    <pythonVersion>${version.python.default}</pythonVersion>
                    <managedDependencies>
                        <packageDefinition>
                            <packageName>ruff</packageName>
                            <operatorAndVersion>>=0.9.9</operatorAndVersion>
                            <!-- optional - active is true by default:-->
                            <active>true</active>
                        </packageDefinition>
                    </managedDependencies>
                    <!-- This will force this or any submodule to be updated: -->
                    <updateManagedDependenciesWhenFound>false</updateManagedDependenciesWhenFound>
                    <!-- This would force a build failure when encountered a version not aligned: -->
                    <failOnManagedDependenciesMismatches>false</failOnManagedDependenciesMismatches>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
