[project]
name = "habushu_managed_dependencies"
version = "3.2.0"
description = "Example of how to use the habushu managed dependencies"
authors = [{name = "Ryan Ashcraft", email = "ryan.ashcraft@codifyiq.com"}]
license = "MIT License"
requires-python = ">=3.12"
dynamic = ["version", "dependencies"]

[tool.poetry.group.dev.dependencies]
behave = ">=1.2.6"
ruff = ">=0.9.9"
kappa-maki = ">=1.0.0"

[build-system]
requires = ["poetry-core>=1.6.0"]
build-backend = "poetry.core.masonry.api"