<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.technologybrewery.habushu</groupId>
        <artifactId>examples</artifactId>
        <version>3.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>uv</artifactId>
    <packaging>pom</packaging>

    <name>habushu::Examples::uv</name>

    <modules>
        <module>habushu-uv-enforcer-rule</module>
        <module>habushu-uv-package</module>
        <module>habushu-uv-package-consumer</module>
        <module>habushu-uv-containerize</module>
        <module>habushu-uv-publish-to-dev-repo</module>
        <module>habushu-uv-install-from-dev-repo</module>
        <module>habushu-uv-dependency-groups</module>
    </modules>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <executions>
                        <execution>
                            <id>enforce-uv</id>
                            <goals>
                                <goal>enforce</goal>
                            </goals>
                            <configuration>
                                <rules>
                                    <requireUvVersion>
                                        <version>>=0.6.0</version>
                                    </requireUvVersion>
                                </rules>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

</project>
